# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/maps/

pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/maps/

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: maps
    Artifacts:
      - name: azure-maps-creator
        safeName: azuremapscreator
      - name: azure-maps-elevation
        safeName: azuremapselevation
      - name: azure-maps-geolocation
        safeName: azuremapsgeolocation
      - name: azure-maps-render
        safeName: azuremapsrender
      - name: azure-maps-route
        safeName: azuremapsroute
      - name: azure-maps-search
        safeName: azuremapssearch
      - name: azure-maps-timezone
        safeName: azuremapstimezone
      - name: azure-maps-traffic
        safeName: azuremapstraffic
      - name: azure-maps-weather
        safeName: azuremapsweather
