/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import {
  OperationParameter,
  OperationURLParameter,
  OperationQueryParameter
} from "@azure/core-client";

export const accept: OperationParameter = {
  parameterPath: "accept",
  mapper: {
    defaultValue: "application/json",
    isConstant: true,
    serializedName: "Accept",
    type: {
      name: "String"
    }
  }
};

export const $host: OperationURLParameter = {
  parameterPath: "$host",
  mapper: {
    serializedName: "$host",
    required: true,
    type: {
      name: "String"
    }
  },
  skipEncoding: true
};

export const clientId: OperationParameter = {
  parameterPath: "clientId",
  mapper: {
    serializedName: "x-ms-client-id",
    type: {
      name: "String"
    }
  }
};

export const apiVersion: OperationQueryParameter = {
  parameterPath: "apiVersion",
  mapper: {
    defaultValue: "1.0",
    isConstant: true,
    serializedName: "api-version",
    type: {
      name: "String"
    }
  }
};

export const acceptLanguage: OperationParameter = {
  parameterPath: ["options", "acceptLanguage"],
  mapper: {
    serializedName: "Accept-Language",
    type: {
      name: "String"
    }
  }
};

export const options: OperationQueryParameter = {
  parameterPath: ["options", "options"],
  mapper: {
    serializedName: "options",
    type: {
      name: "String"
    }
  }
};

export const timeStamp: OperationQueryParameter = {
  parameterPath: ["options", "timeStamp"],
  mapper: {
    serializedName: "timeStamp",
    type: {
      name: "DateTime"
    }
  }
};

export const daylightSavingsTimeFrom: OperationQueryParameter = {
  parameterPath: ["options", "daylightSavingsTimeFrom"],
  mapper: {
    serializedName: "transitionsFrom",
    type: {
      name: "DateTime"
    }
  }
};

export const daylightSavingsTimeLastingYears: OperationQueryParameter = {
  parameterPath: ["options", "daylightSavingsTimeLastingYears"],
  mapper: {
    serializedName: "transitionsYears",
    type: {
      name: "Number"
    }
  }
};

export const format: OperationURLParameter = {
  parameterPath: "format",
  mapper: {
    serializedName: "format",
    required: true,
    type: {
      name: "String"
    }
  }
};

export const timezoneId: OperationQueryParameter = {
  parameterPath: "timezoneId",
  mapper: {
    serializedName: "query",
    required: true,
    type: {
      name: "String"
    }
  }
};

export const coordinates: OperationQueryParameter = {
  parameterPath: "coordinates",
  mapper: {
    constraints: {
      MinItems: 2,
      MaxItems: 2
    },
    serializedName: "query",
    required: true,
    type: {
      name: "Sequence",
      element: {
        type: {
          name: "Number"
        }
      }
    }
  },
  collectionFormat: "CSV"
};

export const windowsTimezoneId: OperationQueryParameter = {
  parameterPath: "windowsTimezoneId",
  mapper: {
    serializedName: "query",
    required: true,
    type: {
      name: "String"
    }
  }
};

export const windowsTerritoryCode: OperationQueryParameter = {
  parameterPath: ["options", "windowsTerritoryCode"],
  mapper: {
    serializedName: "territory",
    type: {
      name: "String"
    }
  }
};
