/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as coreAuth from "@azure/core-auth";
import {
  AliasOperationsImpl,
  DataImpl,
  DatasetOperationsImpl,
  ConversionOperationsImpl,
  FeatureStateOperationsImpl,
  SpatialImpl,
  TilesetOperationsImpl,
  WfsImpl
} from "./operations";
import {
  AliasOperations,
  Data,
  DatasetOperations,
  ConversionOperations,
  FeatureStateOperations,
  Spatial,
  TilesetOperations,
  Wfs
} from "./operationsInterfaces";
import { CreatorClientContext } from "./creatorClientContext";
import { CreatorClientOptionalParams } from "./models";

export class CreatorClient extends CreatorClientContext {
  /**
   * Initializes a new instance of the CreatorClient class.
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param options The parameter options
   */
  constructor(credentials: coreAuth.TokenCredential, options?: CreatorClientOptionalParams) {
    super(credentials, options);
    this.aliasOperations = new AliasOperationsImpl(this);
    this.data = new DataImpl(this);
    this.datasetOperations = new DatasetOperationsImpl(this);
    this.conversionOperations = new ConversionOperationsImpl(this);
    this.featureStateOperations = new FeatureStateOperationsImpl(this);
    this.spatial = new SpatialImpl(this);
    this.tilesetOperations = new TilesetOperationsImpl(this);
    this.wfs = new WfsImpl(this);
  }

  aliasOperations: AliasOperations;
  data: Data;
  datasetOperations: DatasetOperations;
  conversionOperations: ConversionOperations;
  featureStateOperations: FeatureStateOperations;
  spatial: Spatial;
  tilesetOperations: TilesetOperations;
  wfs: Wfs;
}
