/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as coreClient from "@azure/core-client";

/** The response from a successful Get Data for Bounding Box API. */
export interface ElevationResult {
  /**
   * The response for point/points elevation API. The result will be in same sequence of points listed in request.
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly elevations?: Elevation[];
}

/** The elevation data. */
export interface Elevation {
  /** A location represented as a latitude and longitude. */
  coordinate?: LatLongPair;
  /**
   * The elevation value in meters.
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly elevationInMeter?: number;
}

/** A location represented as a latitude and longitude. */
export interface LatLongPair {
  /** Latitude property */
  latitude?: number;
  /** Longitude property */
  longitude?: number;
}

/** Common error response for all Azure Resource Manager APIs to return error details for failed operations. (This also follows the OData error response format.). */
export interface ErrorResponse {
  /** The error object. */
  error?: ErrorDetail;
}

/** The error detail. */
export interface ErrorDetail {
  /**
   * The error code.
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly code?: string;
  /**
   * The error message.
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly message?: string;
  /**
   * The error target.
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly target?: string;
  /**
   * The error details.
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly details?: ErrorDetail[];
  /**
   * The error additional info.
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly additionalInfo?: ErrorAdditionalInfo[];
}

/** The resource management error additional info. */
export interface ErrorAdditionalInfo {
  /**
   * The additional info type.
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly type?: string;
  /**
   * The additional info.
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly info?: Record<string, unknown>;
}

/** A location represented as a latitude and longitude using short names 'lat' & 'lon'. */
export interface LatLongPairAbbreviated {
  /** Latitude property */
  lat?: number;
  /** Longitude property */
  lon?: number;
}

/** Known values of {@link JsonFormat} that the service accepts. */
export enum KnownJsonFormat {
  /** [The JavaScript Object Notation Data Interchange Format](https://tools.ietf.org/html/rfc8259) */
  Json = "json"
}

/**
 * Defines values for JsonFormat. \
 * {@link KnownJsonFormat} can be used interchangeably with JsonFormat,
 *  this enum contains the known values that the service supports.
 * ### Known values supported by the service
 * **json**: [The JavaScript Object Notation Data Interchange Format](https:\/\/tools.ietf.org\/html\/rfc8259)
 */
export type JsonFormat = string;

/** Optional parameters. */
export interface ElevationClientGetDataForPointsOptionalParams
  extends coreClient.OperationOptions {}

/** Contains response data for the getDataForPoints operation. */
export type ElevationClientGetDataForPointsResponse = ElevationResult;

/** Optional parameters. */
export interface ElevationClientPostDataForPointsOptionalParams
  extends coreClient.OperationOptions {}

/** Contains response data for the postDataForPoints operation. */
export type ElevationClientPostDataForPointsResponse = ElevationResult;

/** Optional parameters. */
export interface ElevationClientGetDataForPolylineOptionalParams
  extends coreClient.OperationOptions {
  /** The samples parameter specifies the number of equally spaced points at which elevation values  should be provided along a polyline path. The number of samples should range from 2 to 2,000. Default value is 10. */
  samples?: number;
}

/** Contains response data for the getDataForPolyline operation. */
export type ElevationClientGetDataForPolylineResponse = ElevationResult;

/** Optional parameters. */
export interface ElevationClientPostDataForPolylineOptionalParams
  extends coreClient.OperationOptions {
  /** The samples parameter specifies the number of equally spaced points at which elevation values  should be provided along a polyline path. The number of samples should range from 2 to 2,000. Default value is 10. */
  samples?: number;
}

/** Contains response data for the postDataForPolyline operation. */
export type ElevationClientPostDataForPolylineResponse = ElevationResult;

/** Optional parameters. */
export interface ElevationClientGetDataForBoundingBoxOptionalParams
  extends coreClient.OperationOptions {}

/** Contains response data for the getDataForBoundingBox operation. */
export type ElevationClientGetDataForBoundingBoxResponse = ElevationResult;

/** Optional parameters. */
export interface ElevationClientOptionalParams extends coreClient.ServiceClientOptions {
  /** server parameter */
  $host?: string;
  /** Specifies which account is intended for usage in conjunction with the Azure AD security model.  It represents a unique ID for the Azure Maps account and can be retrieved from the Azure Maps management  plane Account API. To use Azure AD security in Azure Maps see the following [articles](https://aka.ms/amauthdetails) for guidance. */
  clientId?: string;
  /** Api Version */
  apiVersion?: string;
  /** Overrides client endpoint. */
  endpoint?: string;
}
