/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { SearchImpl } from "./operations";
import { Search } from "./operationsInterfaces";
import { SearchClientContext } from "./searchClientContext";
import { SearchClientOptionalParams } from "./models";

export class SearchClient extends SearchClientContext {
  /**
   * Initializes a new instance of the SearchClient class.
   * @param options The parameter options
   */
  constructor(options?: SearchClientOptionalParams) {
    super(options);
    this.search = new SearchImpl(this);
  }

  search: Search;
}
